# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  #
# /* wallust template - colors-kitty */

foreground         #F0F0F0
background         #252525
cursor             #8B8B8B

active_tab_foreground     #252525
active_tab_background     #F0F0F0
inactive_tab_foreground   #F0F0F0
inactive_tab_background   #252525

active_border_color   #F0F0F0
inactive_border_color #252525
bell_border_color     #1C1C1C

color0      #4B4B4B
color1		#1C1C1C
color2		#1C1C1C
color3		#555555
color4		#555555
color5		#8B8B8B
color6		#9F9F9F
color7		#E1E1E1
color8		#9E9E9E
color9		#252525
color10		#262626
color11		#717171
color12		#717171
color13		#B9B9B9
color14		#D4D4D4
color15		#E1E1E1
