w-1=/home/akshay/.config/wallpapers/custom/HwOKHlK.jpeg
w-2=/home/akshay/.config/wallpapers/defaults/sfw/wallhaven-qrjq8l.png
w-3=/home/akshay/.config/wallpapers/defaults/sfw/wallhaven-polpoe.jpg
w-4=/home/akshay/.config/wallpapers/defaults/sfw/wallhaven-5yz968.jpg
w-5=/home/akshay/.config/wallpapers/defaults/sfw/wallhaven-w51kxr.jpg
w-6=/home/akshay/.config/wallpapers/defaults/sfw/wallhaven-zpzv7j.jpg
w-7=/home/akshay/.config/wallpapers/defaults/sfw/__guts_griffith_and_casca_neon_genesis_evangelion_and_2_more_drawn_by_spencer_sais__2a39d1e593cc0925ab32f4cca63854e7.png
w-8=/home/akshay/.config/wallpapers/defaults/sfw/wallhaven-d8395l.jpg
w-9=/home/akshay/.config/wallpapers/defaults/sfw/__gigi_murin_hololive_and_1_more_drawn_by_mazo_kunn__ce79dc4353279954ee6d54f0c3fb4650.jpg
w-10=/home/akshay/.config/wallpapers/defaults/sfw/__world_is_fleeting_as_foam_nikki_and_1_more_drawn_by_xxyt_xx__5f9486e7eac9a0da590f13a6cf45dab6.jpg
